---
title: "R Notebook"
output: html_notebook
---

```{r}
us.rgdp<-read.csv("USRGDP IMF WEO.csv",header=FALSE)
us.rgdp<-us.rgdp[c(1,3),2:44]
us.rgdp<-t(us.rgdp)
us.rgdp[c(1:3,nrow(us.rgdp)),]
colnames(us.rgdp)<-paste(c("Year","Value"))
rownames(us.rgdp)<-seq(1,nrow(us.rgdp),1)
us.rgdp<-data.frame(us.rgdp)
us.rgdp[c(1:3,nrow(us.rgdp)),]
```

```{r}
us.rgdp$historical<-ifelse(us.rgdp$Year<=2016,us.rgdp$Value,0)
us.rgdp[c(1:3,nrow(us.rgdp)),]
us.rgdp$projected<-ifelse(us.rgdp$Year>2016,us.rgdp$Value,0)
us.rgdp[c(1:3,nrow(us.rgdp)),]
us.rgdp<-us.rgdp[,3:4]
us.rgdp[c(1:3,nrow(us.rgdp)),]
```

```{r}
us.mat<-as.matrix(us.rgdp)
t.us<-t(us.mat)
head(t.us)
```

```{r}
xlabel=seq(1980,2022,by=1)
even.years<-xlabel %% 2==0
even.years
```

```{r}
years.even<-cbind(data.frame(xlabel),data.frame(even.years))
xlabel.even<-years.even[,3]
head(xlabel.even)
```

```{r}
range(us.rgdp)
```

```{r}
y.range<-c(-4,8)
y.range
```
```{r}
barplot(t.us,col=c("black","gray60"), ylab="Real GDP Growth (%)", ylim=y.range, names.arg=xlabel.even, las=2, main="United States Real GDP Growth Historical (1980-2022) and Forecasted (2013-2022)")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


